### ISSUE TITLE
View5D under Windows `Class Not Found view5d/View5D`

### ISSUE THREAD

**Issue by roflmaostc** [RainerHeintzmann/View5D.jl#10]
Under windows
```julia
] add View5D
using View5D
@vv randn((5,5))
```
failed with the error
```
ERROR: JavaCall.JavaCallError("Class Not Found view5d/View5D")
```

**Comment by RainerHeintzmann** [comment]
I was unable to reproduce the error. I started a new REPL, activated a temp environment and added View5D:
```julia
(Development) pkg> activate --temp
  Activating new environment at `C:\Users\pi96doc\AppData\Local\Temp\jl_XztOZL\Project.toml`

(jl_XztOZL) pkg> add View5D
```
and ran the commands you suggested, but there was no error on my system.

**Comment by roflmaostc** [comment]
I'll try further digging when I'm back on my windows machine.

**Comment by RainerHeintzmann** [comment]
could have potentially been an accidental use of JavaCall before importing `View5D`.
