### ISSUE TITLE
set_axis_scales_and_units() for all times and elements

### ISSUE THREAD

**Issue by jusack** [RainerHeintzmann/View5D.jl#11]
When changing the axis settings I noticed, that the settings were just updated for the element and time index, that I chose as parameters (or 0 as the default) in [set_axis_scales_and_units()](https://github.com/RainerHeintzmann/View5D.jl/blob/71d53edbf2d47c026fa3a0e3650edd4ee359ac8a/src/View5D.jl#L365). Is there a way to set this automatically for all elements and times except wrapping it in a loop? The comment in L374 seems to suggest this kind of functionality

**Comment by RainerHeintzmann** [comment]
Thanks for this issue. So far the function did not support that but I now added this functionality. The function now accepts ranges and the colon symbol. I added support for AxisArrays, which should be the preferred way of setting axis scales and units. E.g.:
```julia
using Unitful, AxisArrays;
@vv AxisArray(rand(10,11,12,3,4),(:x,:y,:z,:liftetime, :time),(0.1u"µm",0.2u"m",0.3u"µm",1.0u"ns",2.0u"s"))
```
should do the trick.

Please have a try and tell me if you see any bug. Then I can do a release.
Please notice, that the functionality of `set_axis_scales_and_units` has changed, the default being now to update all elements and tines.
